[project]
name = "lunarlander"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gymnasium[box2d]>=1.0.0",
    "stable-baselines3>=2.5.0",
    "swig>=4.3.0",
]
